version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      # Run tests first of all (if this fails we won't go to the effort of running full tox tests)
      - run: python setup.py test

      # Install pyenv for tox tests
      - run: sudo curl https://pyenv.run | bash
      - run: echo 'export PATH="/home/circleci/.pyenv/bin:$PATH"' >> $BASH_ENV
      - run: pyenv install 3.7.5
      - run: pyenv install 3.8.2
      - run: pyenv global 3.8.2 3.7.5

      # Setup and run tox tests
      - run: sudo pip install --upgrade pip
      - run: pip install tox
      - run: tox

workflows:
  branch-build:
    jobs:
      - build-and-test:
          context: development
