workflows:
  version: 2.1
  build-with-approval:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold

version: 2.1
jobs:
  build:
    working_directory: ~/circle-ci-test
    docker:
      - image: circleci/python:3.8.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout

      # TODO: Implement caching

      # Install pyenv for tox tests
      - run: sudo curl https://pyenv.run | bash
      - run: echo 'export PATH="/home/circleci/.pyenv/bin:$PATH"' >> $BASH_ENV
      - run: pyenv install 3.8.10
      - run: pyenv install 3.9.18
      - run: pyenv install 3.10.6
      - run: pyenv install 3.11.3
      - run: pyenv install 3.12.1
      - run: pyenv global 3.8.10 3.9.18 3.10.6 3.11.3 3.12.1

      # Setup and run tox tests
      - run: sudo pip install --upgrade pip
      - run: pip install tox
      - run: tox
